<?php

/**
 * Define Robo commands for building and testing Drupal User Registry Codeception module.
 *
 * @see http://robo.li/
 */
class RoboFile extends \Robo\Tasks
{
    /**
     * @type string
     *   Location of directory containing source code.
     */
    const SRC_DIR = "src";

    /**
     * @type string
     *   Location of directory containing documentation files.
     */
    const DOCS_DIR = "docs";

    /**
     * @type string
     *   Location of directory within DOCS_DIR to contain files generated by PhpDocumentor.
     */
    const PHPDOC_DOCS_SUBDIR = "phpdoc";

    /**
     * @type string
     *   Location of directory within DOCS_DIR to contain files generated by PHP_CodeCoverage.
     */
    const COVERAGE_DOCS_SUBDIR = "coverage";

    /**
     * @type string
     *   Location of directory containing Codeception tests.
     */
    const TESTS_DIR = "tests";

    /**
     * @type string
     *   Path to Codeception.
     */
    const CODECEPTION_PATH = "vendor/bin/codecept";

    /**
     * Run PHP_CodeSniffer standards checks.
     */
    public function cleanupPhpcs()
    {
        $directories = [self::SRC_DIR, self::TESTS_DIR];

        foreach ($directories as $directory) {
            $this->taskExec("phpcs --standard=PSR2 " . $directory)
                ->printed(false)
                ->run();
        }
    }

    /**
     * Regenerate all documentation files.
     */
    public function docsGenerate()
    {
        $this->docsClean();
        $this->docsPhpdoc();
        $this->docsCoverage();
    }

    /**
     * Generate PhpDocumentor files.
     */
    public function docsPhpdoc()
    {
        $this->taskExec("phpdoc run")->run();
    }

    /**
     * Run unit tests + coverage and copy to docs/coverage/ directory.
     */
    public function docsCoverage()
    {
        $this->taskDeleteDir(self::DOCS_DIR . DIRECTORY_SEPARATOR . self::COVERAGE_DOCS_SUBDIR)->run();
        $this->testsCoverage();
        $this->taskCopyDir([
            "tests/_output/coverage" => self::DOCS_DIR . DIRECTORY_SEPARATOR . self::COVERAGE_DOCS_SUBDIR
        ])->run();
    }

    /**
     * Clean entire documentation directory.
     */
    public function docsClean()
    {
        $this->taskCleanDir(self::DOCS_DIR)->run();
    }

    /**
     * Build Codeception's auto-generated files.
     */
    public function testsBuild()
    {
        $this->taskExec(sprintf("%s build", self::CODECEPTION_PATH))->run();
    }

    /**
     * Run (functional) tests.
     */
    public function testsRun()
    {
        // Still have to build the *Tester classes if we've just checked out.
        $this->testsBuild();

        foreach (["unit", "acceptance"] as $suite) {
            $this->taskCodecept(self::CODECEPTION_PATH)
                ->option("config", "codeception.yml")
                ->suite($suite)
                ->run();
        }
    }

    /**
     * Run CodeCoverage.
     */
    public function testsCoverage()
    {
        // Unable to use taskCodecept() here as "Executing vendor/bin/codecept run --coverage-html unit" actually runs
        // the acceptance suite too. The syntax below (with suite before options) seems to work:
        //
//        $this->taskCodecept(self::CODECEPTION_PATH)
//            ->suite("unit")
//            ->option("coverage-html")
//            ->run();
        // @todo Investigate and submit issue.
        $this->taskExec(self::CODECEPTION_PATH . " run unit --coverage-html")->run();
    }
}
